// -----------------------------------------------------------------------
// <copyright file="QuizeManagerEvents.cs" company="DjayEnglish">
// Copyright (c) DjayEnglish. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace DjayEnglish.Server.Core
{
    using System;
    using DjayEnglish.Server.ObjectModels;

    /// <summary>
    /// Global events generated by quize managers.
    /// </summary>
    public class QuizeManagerEvents
    {
        /// <summary>
        /// Notify all listeners subscribed that quize started.
        /// </summary>
        public event EventHandler<OnQuizeStartedEventArgs>? OnQuizeStarted;

        /// <summary>
        /// Notify all listeners subscribed that user answer result recived.
        /// </summary>
        public event EventHandler<OnUserAnswerResultEventArgs>? OnUserAnswerResultRecived;

        /// <summary>
        /// Notify that quize started.
        /// </summary>
        /// <param name="chatId">Id of the chat where quize started.</param>
        /// <param name="quize">Quize model which was started.</param>
        public void NotifyQuizeStarted(long chatId, Quize quize)
        {
            this.OnQuizeStarted?.Invoke(this, new OnQuizeStartedEventArgs(chatId, quize));
        }

        /// <summary>
        /// Notify that user answer result was recived.
        /// </summary>
        /// <param name="chatId">Id of the chat where user answer on quize.</param>
        /// <param name="isAnswerRight">Indicate that user answer was right.</param>
        public void NotifyUserAnswerResultRecived(long chatId, bool isAnswerRight)
        {
            this.OnUserAnswerResultRecived?.Invoke(this, new OnUserAnswerResultEventArgs(chatId, isAnswerRight));
        }
    }
}
